### ISSUE TITLE
JavaScript版的 widget 什么时候可以用上？

### ISSUE THREAD

**Issue by netcore-jroger** [rongcloud/rongcloud-web-im-widget#1]
如题：JavaScript版的 widget 什么时候可以用上？

**Comment by arielyang** [comment]
是说不依赖于 AngularJS 的版本吗？

**Comment by Oger-Me** [comment]
是的。

**Comment by Oger-Me** [comment]
什么时候会有呢？

**Comment by arielyang** [comment]
用 AngularJS 有什么障碍或者问题吗？

**Comment by xialvjun** [comment]
用angularjs就限制了项目的技术栈啊。。。事实上我还想问问有没有react版本的呢。。。不过，对你们而言，最有利的就是开发一个纯js版本的吧。。。然后其他项目就能够很方便的嵌入这个东西。。。

**Comment by qwerchuan** [comment]
插件之外的代码可以不用angular写的。这个插件使用很简单，不需要熟悉angular按demo写就可以。JavaScript版本的有时间会写一个。

**Comment by CallMeXYZ** [comment]
难道不是应该尽可能解耦？
